[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[graphql]
enabled = true
port = 54322
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
secure_channels = false

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

# A string used to distinguish different Supabase projects on the same host. Defaults to the working directory name.
project_id = "lawless-directory"

[database]
# Port to use for the local database URL.
port = 54322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW server_version;` on the remote database to check.
major_version = 15
# Max file size for CSV imports (in MB)
csv_import_max_file_size = 32

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (1 week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Use an external OAuth provider. The full list of providers are: `apple`, `azure`, `bitbucket`,
# `discord`, `facebook`, `github`, `gitlab`, `google`, `keycloak`, `linkedin`, `notion`, `twitch`,
# `twitter`, `slack`, `spotify`, `workos`, `zoom`.
[auth.external.apple]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[edge_runtime]
enabled = true
# Configure one of the supported poolers. The connection string is then constructed from the passed in
# environment variables like VW_PASSWORD, VW_HOST, VW_PORT, etc.
# If no pooler is configured and VW_PASSWORD is set, Vitagess connection string will be used.
# 1. Supported poolers:
#   - vitagess: "host={VW_HOST} port={VW_PORT} user=postgres password={VW_PASSWORD} sslmode=require"
#   - pgbouncer: "host={PGBOUNCER_HOST} port={PGBOUNCER_PORT} user=postgres password={PGBOUNCER_PASSWORD}"
[experimental.edge_runtime.pooler]
enabled = false